name: Lint
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: 00 12 * * * # 1 hour before Dependabot

permissions: write-all

jobs:
    format:
        name: Format
        if: ${{ always() }} && startsWith(github.ref_name, 'dependabot/') != true
        runs-on: ubuntu-20.04
        needs: bump

        steps:
            - name: Checkout
              uses: actions/checkout@v3.6.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Format
              run: npm run format

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.16.0
              with:
                  commit_message: Format
                  branch: ${{ github.head_ref }}

    analyze:
        name: Analyze
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.6.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup CodeQL
              uses: github/codeql-action/init@v2.3.3
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Analyze
              uses: github/codeql-action/analyze@v2

    build:
        name: Build
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.6.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build
